### ISSUE TITLE
Error in ExtractTracks.py Script

### ISSUE THREAD

**Issue by EEPuckett** [eatkinson/Tractor#6]
I have encounted the following error a few times using the updated ExtractTracts script:
`Traceback (most recent call last):
  File "/home/puckett3/software/Tractor/ExtractTracts.py", line 163, in <module>
    extract_tracts(**vars(args))
  File "/home/puckett3/software/Tractor/ExtractTracts.py", line 106, in extract_tracts
    geno_b = str(geno[1])
IndexError: list index out of range`

I have checked that the number of samples in the VCF is half the number in the MSP file.
I have also run the script changing the second header line in the MSP file from:
#chm	spos	epos	sgpos	egpos	n  snps
to
#chm	spos	epos	sgpos	egpos	nsnps

Yet I get the same error.

Do you have any suggestions for troubleshooting?

With thanks,
Emily

**Comment by eatkinson** [comment]
** resolved over email. **
VCF file was for the entire genome, msp were split by chromosome, causing alignment issues. Earlier versions of this script (https://github.com/eatkinson/Tractor/blob/06275533632103ab5b6520f1365f2692a3039923/ExtractTracts.py) are less flexible for ancestry numbers but do not require files to be harmonized in this way. 
To be updated: allow for chrom msp input in updated script
