### ISSUE TITLE
Switch from per chromosome to autosomes

### ISSUE THREAD

**Issue by heidiesteiner** [eatkinson/Tractor#8]
Hello Dr. Atkinson,

Thank you so much for these scripts and example code. 

In the RFMix_v2 step, your example code produces per chromosome rfmix output. 
In the Extract Tracts step, it's unclear whether you've used per chromosome or an autosome file (I used per chromosome MSP files and VCF files). 
However in the example Hail code you've read in an `autosomes.anc0.dosage.txt` file. 

I'm wondering where, when, and how the autosomes file should be made. Or rather, did you run RFMix_v2 on the whole genome instead of by chromosome as the example suggests? 

Thank you for clarifying! 
Heidi

**Comment by heidiesteiner** [comment]
Still having the same issue. I noticed the previous issue (#6 ) was solved by harmonizing the msp and vcf files. Do the msp and vcf files need to be by chromosome or all autosomes?

**Comment by eatkinson** [comment]
Hi Heidi,
Apologies I missed this. To make the autosomes file I simply concatenated all the individual chromosome files output by RFmix together prior to running the Tractor scripts. This way I only needed to launch one job to run tractor GWAS across all the autosomes. You could still run things on a chromosome by chromosome basis, however if that is preferable - both options should work now as the code has been updated.
Let me know if this works!
Best,
Elizabeth
